- name: Install Prometheus Node Exporter
  hosts: all
  become: yes
  vars:
    node_exporter_link: "https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz"
    version: node_exporter-1.5.0.linux-amd64
    node_exporter_port: 9101
    node_exporter_user: node_exporter

  tasks:
    - name: Check if port is in use
      wait_for:
        port: "{{ node_exporter_port }}"
        state: absent
      register: port_check

    - name: Print message and stop task if port is in use
      fail:
        msg: "Port {{ node_exporter_port }} is in use, installation cannot continue"
      when: port_check.failed


    - name: Download and install Node Exporter
      get_url:
        url: "{{ node_exporter_link }}"
        dest: "/tmp/node_exporter.tar.gz"

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/usr/local"
        remote_src: yes


    - name: Create a symbolic link for Node Exporter
      copy:
        remote_src: true
        src: "/usr/local/{{ version }}/node_exporter"
        dest: "/usr/local/bin/node_exporter"

    - name: Create node_exporter user
      user:
        name: "{{ node_exporter_user }}"
        state: present

    - name: copy file between locations on the remote host
      copy:
        src: ./node_exporter.service
        dest: /etc/systemd/system/



    - name: Enable the service
      systemd:
        name: node_exporter
        state: started
        enabled: yes

    - name: Start the service
      systemd:
        name: node_exporter
        state: started

    - name: Show status of the service
      command: systemctl status node_exporter
      register: service_status

    - name: Display the result
      debug:
        var: service_status.stdout_lines
